### ISSUE TITLE
How to create one-way connections?

### ISSUE THREAD

**Issue by sualko** [otalk/jingle-media-session#27]
I would like to broadcast my stream to another user without receiving his stream. I can set `offerToReceiveAudio|Video` to false, but how can I get this information on the other side? Or is there an other way to achieve this, because `offerToReceiveAudio` is completely gone from the [spec](https://www.w3.org/TR/webrtc/).

**Comment by fippo** [comment]
offerToReceive is gone from the spec but the alternative is not implemented yet so that stuff is still supported.

You should see a different senders attribute on the content when creating such an offer -- which should map back to a=sendonly/recvonly or sendrecv (I think inactive isn't supported...)

**Comment by sualko** [comment]
Thank you for this hint. Maybe my solution is helpful for someone else, so here we go:

If the other peer does not request audio/video the value for `session.pc.remoteDescription.contents[x].senders` is `initiator`, otherwise `both`. See also [XEP-0167](https://xmpp.org/extensions/xep-0167.html#negotiation)
